[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
tokio = { version = "1", features = ["full"] }
ioc_container_rs = { version = "0.0.1" }
kti_cqrs_provider_rs = { path = "../kti_cqrs_provider_rs" }
