[package]
name = "example"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kti_cqrs_provider_rs = { path = "../kti_cqrs_provider_rs" }
async-trait = { workspace = true }
tokio = { workspace = true }
ioc_container_rs = { workspace = true }
