[package]
name = "example"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.83"
tokio = { version = "1.42.0", features = ["sync", "time"] }
ioc_container_rs = { version = "0.2.0" }
kti_cqrs_provider_rs = { path = "../kti_cqrs_provider_rs" }
