[package]
name = "kti_cqrs_provider_rs"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "CQRS provider with ioc container"
homepage = "https://github.com/kotletti/kti_cqrs_provider_rs"
repository = "https://github.com/kotletti/kti_cqrs_provider_rs"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ioc_container_rs = { version = "0.2.0" }
kti_cqrs_rs = { git = "https://github.com/kotletti/kti_cqrs_rs", branch = "rc-0.3.0" }
# kti_cqrs_rs = { version = "0.2.0" }
tokio = { version = "1.42.0", features = ["sync"] }
async-trait = "0.1.83"
