[package]
name = "kti_cqrs_provider_rs"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CQRS provider with ioc container"
homepage = "https://github.com/kotletti/kti_cqrs_provider_rs"
repository = "https://github.com/kotletti/kti_cqrs_provider_rs"
readme = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ioc_container_rs = { workspace = true }
kti_cqrs_rs = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
